# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clips', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cropping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('c_year', models.DateTimeField()),
                ('c_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('income', models.IntegerField()),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_lat', models.FloatField()),
                ('P_long', models.FloatField()),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_lat', models.FloatField()),
                ('w_long', models.FloatField()),
                ('well_water_depth', models.FloatField()),
                ('avg_wateryield', models.FloatField()),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Wellyield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_depth', models.FloatField()),
                ('date', models.DateField(null=True)),
                ('wateryield', models.FloatField()),
                ('well_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Well')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='H_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Household'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='F_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Farm'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='crop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Crop'),
        ),
        migrations.AddField(
            model_name='audio',
            name='H_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task3app.Household'),
        ),
    ]
