# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropping',
            name='season_id',
        ),
        migrations.AddField(
            model_name='cropping',
            name='season',
            field=models.CharField(choices=[('1', 'Summer'), ('2', 'Rainy'), ('3', 'Winter'), ('4', 'Monsoon')], default='Summer', max_length=20),
            preserve_default=False,
        ),
    ]
